version: 2

models:
  - name: ex4_fct_orders_enriched
    description: >
      Exercise 4 — One row per order across 2022–2023 with the total quantity of products (qty_product).
      This table standardizes orders for downstream analytics.
    columns:
      - name: order_id
        description: "Unique order identifier."
        tests: [not_null, unique]
      - name: client_id
        description: "Customer identifier for the order."
        tests: [not_null]
      - name: order_date
        description: "Date the order was placed."
        tests: [not_null]
      - name: qty_product
        description: "Total number of products in the order (sum of sales line quantities)."
        tests: [not_null]
      - name: net_sales
        description: "Total net sales amount for the order (sum of line net_sales)."
        tests: [not_null]  

  - name: ex5_fct_orders_segmentation_2023
    description: >
      Exercise 5 — For each 2023 order, classify the order into a segment based on the customer's
      prior 12-month order count:
      - New: 0 prior orders in the last 12 months
      - Returning: 1–3 prior orders in the last 12 months
      - VIP: 4+ prior orders in the last 12 months
    columns:
      - name: order_id
        description: "Unique order identifier for the 2023 order being segmented."
        tests: [not_null, unique]
      - name: client_id
        description: "Customer identifier associated with the order."
        tests: [not_null]
      - name: order_date
        description: "Order date (2023 only)."
        tests: [not_null]
      - name: prior_12m_orders
        description: "Number of orders placed by this customer during the 12 months prior to order_date."
      - name: order_segmentation
        description: "Segment label: 'New', 'Returning', or 'VIP' derived from prior_12m_orders."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['New', 'Returning', 'VIP']
                quote: true

  - name: ex6_fct_orders_2023_with_segmentation
    description: >
      Exercise 6 — One row per 2023 order including qty_product and the order_segmentation label.
      Join of ex4 (enriched orders) and ex5 (segmentation).
    columns:
      - name: order_id
        description: "Unique order identifier for 2023 orders."
        tests: [not_null, unique]
      - name: client_id
        description: "Customer identifier."
        tests: [not_null]
      - name: order_date
        description: "Order date (2023 only)."
        tests: [not_null]
      - name: qty_product
        description: "Total number of products in the order (from ex4)."
        tests: [not_null]
      - name: net_sales
        description: "Alias of order_revenue for compatibility."
      - name: order_segmentation
        description: "Segment label for the order (from ex5)."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['New', 'Returning', 'VIP']
                quote: true
